# Generated by Django 6.0.5 on 2026-05-26 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_evento', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('emoji', models.CharField(choices=[('🎈', '🎈'), ('⚽', '⚽'), ('🃏', '🃏'), ('♟️', '♟️'), ('🎲', '🎲'), ('🏀', '🏀')], default='🃏', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
